### ISSUE TITLE
Need a build process for this tool

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/template2helm#1]
We probably want to add a Makefile and some automation to build/release the tool

**Comment by ch-stark** [comment]
when installing 
 make all worked.  (make install didn't create template2helm)

**Comment by etsauer** [comment]
@ch-stark can you provide some more detail? `make install` seems to work for me.

**Comment by ch-stark** [comment]
@etsauer I did the steps on a new RHEL 8 hosts. I need some time till I can repeat that

**Comment by cpitman** [comment]
@etsauer Is this issue done, between `make` and GitHub Actions? Or is there something left to do?

**Comment by etsauer** [comment]
@cpitman I think we can close it.
