### ISSUE TITLE
Migrate release process to GitHub Actions

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/template2helm#15]
Looking at canned github actions for more and more of our workflows, I think that these two actions provide most of the functionality that we currently have in the Makefile:

- https://github.com/marketplace/actions/create-a-release
- https://github.com/marketplace/actions/upload-a-release-asset

The things I see that may be missing right now are:

- *The ability to upload a whole directory of binaries.* I would rather not have to maintain a unique config for every binary we upload. This would require updating multiple configs to add new binaries. So far the only examples I've seen working do one at a time, such as https://github.com/tylerauerbeck/dash/blob/master/.github/workflows/release.yml#L35-L74
- *The ability to use `git log` to generate my release body text.* From what I understand, the create-release plugin doesn't pull the whole git tree, so the log isn't possible in that context.

**Comment by cpitman** [comment]
This action looks promising: https://github.com/softprops/action-gh-release/blob/master/README.md

**Comment by etsauer** [comment]
@cpitman started working on a little something in my fork:

https://github.com/etsauer/template2helm/releases
https://github.com/etsauer/template2helm/blob/master/.github/workflows/release.yml

Looks promising so far, but still a few kinks to work out.
