### ISSUE TITLE
Generate helm chart from live resources

### ISSUE THREAD

**Issue by siamaksade** [redhat-cop/template2helm#19]
A customer that is using `template2helm` asked if it could expand the use-cases to be able to do the same for live k8s and openshift objects and produce a chart. For example based on a label selector.

**Comment by InfoSec812** [comment]
I would *LOVE* to see this. That said, it's not really that difficult to do using either `kubectl` or `oc`...

**Comment by InfoSec812** [comment]
@siamaksade I was able to quickly script it this way:

```
for I in $(oc get all -o=custom-columns=VER:.apiVersion,KIND:.kind,NAME:.metadata.name | grep -v ReplicationController | grep -v Pod | grep -v "^VER" | awk '{print $2"/"$3}')
do
    oc get ${I} -o yaml > /tmp/chart_export/$(echo $I | sed 's@/@_@g').yaml
done
```

**Comment by etsauer** [comment]
@InfoSec812 yeah, its not terribly difficult to get the YAML. The more challenging part is that the yaml that you get from the cluster will include lots of fields that you don't want in your template. It would be easy enough to clean up the `.metadata` and `status` sections, but what about generated fields in the resource's `spec`?

Also, here's a more native way to handle the loop above:
```
resources=$(oc get all -l app.kubernetes.io/name -n basic-nginx-dev -o jsonpath='{range .items[?(@.kind!="ReplicationController")]}{.kind}{"/"}{.metadata.name}{" "}{end}')

for resource in $resources; do 
   oc get $resource -n basic-nginx-dev -o yaml
done
```

**Comment by etsauer** [comment]
@siamaksade this makes me wonder... what ever happened to `oc export`? something like that would come in handy right about now.

**Comment by InfoSec812** [comment]
@etsauer I had the same thought, but `oc export` has been deprecated for God knows what reason.... >:|

**Comment by etsauer** [comment]
yeah, if we were to incorporate this feature into the tool, we'd basically be talking about bring back that filtering logic.

**Comment by siamaksade** [comment]
`--export` deprecation has a long story but the short version is that it didn't do that good a job of it. You can read more on the PR:
https://github.com/kubernetes/kubernetes/pull/73787

Even though cleaning just the `.metadata` might not produce a final chart, it would still be sufficiently useful IMO as it gets most of the job done and just requires the users to do some minor manual cleanings. The alternative for the user is to manually do everything that the tool does in addition to the manual cleanings that he has to do.

**Comment by etsauer** [comment]
ok, so we would have the tool collect as input:

- a name for the chart
- an output directory
- a label selector
- (optional) a namespace

And we'll get all resource types, except for an exception list of certain types like Pods, ReplicationControllers, etc., and output it to yaml, filtering out some `.metadata` fields, and the `.status` section.

Sound good?

**Comment by siamaksade** [comment]
It definitely does. Chartify is a similar tool that does this but it's limited to k8s objects:
https://github.com/kubepack/chartify/blob/master/pkg/kube_objects.go#L20

**Comment by InfoSec812** [comment]
Hmmm... Thanks for that link! I opened an issue on their side to add support for retrieving the list of resource types from the cluster... Perhaps there is an opportunity for collaboration there?

**Comment by garethahealy** [comment]
archiving
