### ISSUE TITLE
Binary for mac-arm64-template2helm

### ISSUE THREAD

**Issue by chiefrocker86** [redhat-cop/template2helm#26]
Are there plans to publish a mac-arm64-template2helm binary for m1/m2-based MacOS?
Alternatively: how could one build one using the sources available here?

**Comment by garethahealy** [comment]
@chiefrocker86 ; nope, but if you want to tweak the make/release process, am happy to review/merge:
- https://github.com/redhat-cop/template2helm/blob/master/.github/workflows/release.yml#L36-L46
- https://github.com/redhat-cop/template2helm/blob/master/Makefile#L21

**Comment by garethahealy** [comment]
archiving
