### ISSUE TITLE
Idea: Ship it as a Github Action

### ISSUE THREAD

**Issue by howprobable** [redhat-cop/template2helm#27]
Why dont you make a github action out of it? A binary is sometimes problematic with company devices

**Comment by garethahealy** [comment]
@howprobable am not sure how providing a github action really helps. this tool is a run-once operation. so how would providing an action help people move from OCP templates to Helm charts?

also note, this repo is not active. so even if there were great reasons for an action, it would need to be contributed by yourself.

**Comment by howprobable** [comment]
In some companies I have seen, the security risk engineering team will knock on your office door the second you click the download button for a binary. A pull-change-push GH action to convert the templates once would solve that. :) 

But you are right, I could contribute it myself. Just wanted to place the Idea.

**Comment by garethahealy** [comment]
archiving
