### ISSUE TITLE
Creates Wrong Chart for Template with Multiple Resources of a Single Kind

### ISSUE THREAD

**Issue by cpitman** [redhat-cop/template2helm#4]
When naming files in the helm chart, the current implementation names each file using only the `kind` of the resource being created. For example, `service.yaml`, `route.yaml`, etc. This will produce incorrect results when there are two resources of the same kind, like two `Service`s.

https://github.com/redhat-cop/template2helm/blob/master/cmd/convert.go#L111

A possible fix would be to add the resource name to the kind, which should always be unique within a single namespace.

**Comment by etsauer** [comment]
resolved by #9
